//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:CreaDoc:modelo:sap", ConfigurationName="SI_Documento_Out")]
public interface SI_Documento_Out
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CrearDocumentos_SyncResponse> CrearDocumentos_SyncAsync(CrearDocumentos_SyncRequest request);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task CrearDocumentos_AsyncAsync(CrearDocumentos_Async request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:transaccionales:modelo:sap")]
public partial class DocumentosDocumentos
{
    
    private Traza trazaField;
    
    private Documento documentoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public Traza Traza
    {
        get
        {
            return this.trazaField;
        }
        set
        {
            this.trazaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public Documento Documento
    {
        get
        {
            return this.documentoField;
        }
        set
        {
            this.documentoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class Traza
{
    
    private TrazaKey infoClaveField;
    
    private TrazaInfoAdicional infoAdicionalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public TrazaKey InfoClave
    {
        get
        {
            return this.infoClaveField;
        }
        set
        {
            this.infoClaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public TrazaInfoAdicional InfoAdicional
    {
        get
        {
            return this.infoAdicionalField;
        }
        set
        {
            this.infoAdicionalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class TrazaKey
{
    
    private string sociedadField;
    
    private string agenciaField;
    
    private System.DateTime fechaField;
    
    private string interfazField;
    
    private string procesoField;
    
    private string secuenciaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string Sociedad
    {
        get
        {
            return this.sociedadField;
        }
        set
        {
            this.sociedadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Agencia
    {
        get
        {
            return this.agenciaField;
        }
        set
        {
            this.agenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
    public System.DateTime Fecha
    {
        get
        {
            return this.fechaField;
        }
        set
        {
            this.fechaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string Interfaz
    {
        get
        {
            return this.interfazField;
        }
        set
        {
            this.interfazField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string Proceso
    {
        get
        {
            return this.procesoField;
        }
        set
        {
            this.procesoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string Secuencia
    {
        get
        {
            return this.secuenciaField;
        }
        set
        {
            this.secuenciaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class DetalleNotificacion
{
    
    private string posicionField;
    
    private string errorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string Posicion
    {
        get
        {
            return this.posicionField;
        }
        set
        {
            this.posicionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class CabeceraNotificacion
{
    
    private string idDocumentoField;
    
    private string estatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string IdDocumento
    {
        get
        {
            return this.idDocumentoField;
        }
        set
        {
            this.idDocumentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Estatus
    {
        get
        {
            return this.estatusField;
        }
        set
        {
            this.estatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class NotificacionProceso
{
    
    private CabeceraNotificacion cabeceraField;
    
    private DetalleNotificacion[] detalleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public CabeceraNotificacion Cabecera
    {
        get
        {
            return this.cabeceraField;
        }
        set
        {
            this.cabeceraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Detalle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public DetalleNotificacion[] Detalle
    {
        get
        {
            return this.detalleField;
        }
        set
        {
            this.detalleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class Retencion
{
    
    private string tipoRetencionField;
    
    private string indRetencionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string TipoRetencion
    {
        get
        {
            return this.tipoRetencionField;
        }
        set
        {
            this.tipoRetencionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string IndRetencion
    {
        get
        {
            return this.indRetencionField;
        }
        set
        {
            this.indRetencionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class DatosCPD
{
    
    private string nombresField;
    
    private string apellidosField;
    
    private string nIFField;
    
    private string tipoNIFField;
    
    private string tipoDocField;
    
    private string regionField;
    
    private string poblacionField;
    
    private string direccionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string Nombres
    {
        get
        {
            return this.nombresField;
        }
        set
        {
            this.nombresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Apellidos
    {
        get
        {
            return this.apellidosField;
        }
        set
        {
            this.apellidosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string NIF
    {
        get
        {
            return this.nIFField;
        }
        set
        {
            this.nIFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string TipoNIF
    {
        get
        {
            return this.tipoNIFField;
        }
        set
        {
            this.tipoNIFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string TipoDoc
    {
        get
        {
            return this.tipoDocField;
        }
        set
        {
            this.tipoDocField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string Region
    {
        get
        {
            return this.regionField;
        }
        set
        {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string Poblacion
    {
        get
        {
            return this.poblacionField;
        }
        set
        {
            this.poblacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string Direccion
    {
        get
        {
            return this.direccionField;
        }
        set
        {
            this.direccionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class DetalleDocumento
{
    
    private string posicionField;
    
    private string posicionConceptoField;
    
    private decimal valorField;
    
    private bool valorFieldSpecified;
    
    private string nitTerceroField;
    
    private string asignacionField;
    
    private string textoPosicionField;
    
    private string claveReferencia1Field;
    
    private string claveReferencia2Field;
    
    private string centroBeneficioField;
    
    private string centroCostoField;
    
    private string ordenField;
    
    private string indicadorIVAField;
    
    private string sociedadField;
    
    private DatosCPD datosCPDField;
    
    private Retencion[] retencionesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string Posicion
    {
        get
        {
            return this.posicionField;
        }
        set
        {
            this.posicionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string PosicionConcepto
    {
        get
        {
            return this.posicionConceptoField;
        }
        set
        {
            this.posicionConceptoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public decimal Valor
    {
        get
        {
            return this.valorField;
        }
        set
        {
            this.valorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValorSpecified
    {
        get
        {
            return this.valorFieldSpecified;
        }
        set
        {
            this.valorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string NitTercero
    {
        get
        {
            return this.nitTerceroField;
        }
        set
        {
            this.nitTerceroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string Asignacion
    {
        get
        {
            return this.asignacionField;
        }
        set
        {
            this.asignacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string TextoPosicion
    {
        get
        {
            return this.textoPosicionField;
        }
        set
        {
            this.textoPosicionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string ClaveReferencia1
    {
        get
        {
            return this.claveReferencia1Field;
        }
        set
        {
            this.claveReferencia1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string ClaveReferencia2
    {
        get
        {
            return this.claveReferencia2Field;
        }
        set
        {
            this.claveReferencia2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string CentroBeneficio
    {
        get
        {
            return this.centroBeneficioField;
        }
        set
        {
            this.centroBeneficioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string CentroCosto
    {
        get
        {
            return this.centroCostoField;
        }
        set
        {
            this.centroCostoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string Orden
    {
        get
        {
            return this.ordenField;
        }
        set
        {
            this.ordenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string IndicadorIVA
    {
        get
        {
            return this.indicadorIVAField;
        }
        set
        {
            this.indicadorIVAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string Sociedad
    {
        get
        {
            return this.sociedadField;
        }
        set
        {
            this.sociedadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public DatosCPD DatosCPD
    {
        get
        {
            return this.datosCPDField;
        }
        set
        {
            this.datosCPDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Retenciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
    public Retencion[] Retenciones
    {
        get
        {
            return this.retencionesField;
        }
        set
        {
            this.retencionesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class CabeceraDocumento
{
    
    private string codProcesoField;
    
    private string monedaField;
    
    private System.DateTime fechaContField;
    
    private System.DateTime fechaDocumentoField;
    
    private string oficinaVentaField;
    
    private string puntoVentaField;
    
    private string referenciaField;
    
    private string textoCabeceraField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string CodProceso
    {
        get
        {
            return this.codProcesoField;
        }
        set
        {
            this.codProcesoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Moneda
    {
        get
        {
            return this.monedaField;
        }
        set
        {
            this.monedaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
    public System.DateTime FechaCont
    {
        get
        {
            return this.fechaContField;
        }
        set
        {
            this.fechaContField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
    public System.DateTime FechaDocumento
    {
        get
        {
            return this.fechaDocumentoField;
        }
        set
        {
            this.fechaDocumentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string OficinaVenta
    {
        get
        {
            return this.oficinaVentaField;
        }
        set
        {
            this.oficinaVentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string PuntoVenta
    {
        get
        {
            return this.puntoVentaField;
        }
        set
        {
            this.puntoVentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string Referencia
    {
        get
        {
            return this.referenciaField;
        }
        set
        {
            this.referenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string TextoCabecera
    {
        get
        {
            return this.textoCabeceraField;
        }
        set
        {
            this.textoCabeceraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:transaccionales:modelo:sap")]
public partial class Documento
{
    
    private CabeceraDocumento cabeceraField;
    
    private DetalleDocumento[] detalleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public CabeceraDocumento Cabecera
    {
        get
        {
            return this.cabeceraField;
        }
        set
        {
            this.cabeceraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Detalle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public DetalleDocumento[] Detalle
    {
        get
        {
            return this.detalleField;
        }
        set
        {
            this.detalleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:globales:modelo:sap")]
public partial class TrazaInfoAdicional
{
    
    private System.DateTime horaField;
    
    private bool horaFieldSpecified;
    
    private string generico1Field;
    
    private string generico2Field;
    
    private string generico3Field;
    
    private string generico4Field;
    
    private string generico5Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=0)]
    public System.DateTime Hora
    {
        get
        {
            return this.horaField;
        }
        set
        {
            this.horaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HoraSpecified
    {
        get
        {
            return this.horaFieldSpecified;
        }
        set
        {
            this.horaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Generico1
    {
        get
        {
            return this.generico1Field;
        }
        set
        {
            this.generico1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string Generico2
    {
        get
        {
            return this.generico2Field;
        }
        set
        {
            this.generico2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string Generico3
    {
        get
        {
            return this.generico3Field;
        }
        set
        {
            this.generico3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string Generico4
    {
        get
        {
            return this.generico4Field;
        }
        set
        {
            this.generico4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string Generico5
    {
        get
        {
            return this.generico5Field;
        }
        set
        {
            this.generico5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:globales:modelo:sap")]
public partial class NotificacionMensajeNotificacion
{
    
    private Traza trazaField;
    
    private NotificacionProceso notificacionProcesoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public Traza Traza
    {
        get
        {
            return this.trazaField;
        }
        set
        {
            this.trazaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public NotificacionProceso NotificacionProceso
    {
        get
        {
            return this.notificacionProcesoField;
        }
        set
        {
            this.notificacionProcesoField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CrearDocumentos_SyncRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:transaccionales:modelo:sap", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Documentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DocumentosDocumentos[] DocumentosRequest;
    
    public CrearDocumentos_SyncRequest()
    {
    }
    
    public CrearDocumentos_SyncRequest(DocumentosDocumentos[] DocumentosRequest)
    {
        this.DocumentosRequest = DocumentosRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CrearDocumentos_SyncResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:globales:modelo:sap", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Notificacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NotificacionMensajeNotificacion[] NotificacionMensajeResponse;
    
    public CrearDocumentos_SyncResponse()
    {
    }
    
    public CrearDocumentos_SyncResponse(NotificacionMensajeNotificacion[] NotificacionMensajeResponse)
    {
        this.NotificacionMensajeResponse = NotificacionMensajeResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CrearDocumentos_Async
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:transaccionales:modelo:sap", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Documentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DocumentosDocumentos[] Documentos;
    
    public CrearDocumentos_Async()
    {
    }
    
    public CrearDocumentos_Async(DocumentosDocumentos[] Documentos)
    {
        this.Documentos = Documentos;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public interface SI_Documento_OutChannel : SI_Documento_Out, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public partial class SI_Documento_OutClient : System.ServiceModel.ClientBase<SI_Documento_Out>, SI_Documento_Out
{
    
    /// <summary>
    /// Implemente este método parcial para configurar el punto de conexión de servicio.
    /// </summary>
    /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
    /// <param name="clientCredentials">Credenciales de cliente</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public SI_Documento_OutClient(EndpointConfiguration endpointConfiguration) : 
            base(SI_Documento_OutClient.GetBindingForEndpoint(endpointConfiguration), SI_Documento_OutClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SI_Documento_OutClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(SI_Documento_OutClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SI_Documento_OutClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(SI_Documento_OutClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SI_Documento_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CrearDocumentos_SyncResponse> SI_Documento_Out.CrearDocumentos_SyncAsync(CrearDocumentos_SyncRequest request)
    {
        return base.Channel.CrearDocumentos_SyncAsync(request);
    }
    
    public System.Threading.Tasks.Task<CrearDocumentos_SyncResponse> CrearDocumentos_SyncAsync(DocumentosDocumentos[] DocumentosRequest)
    {
        CrearDocumentos_SyncRequest inValue = new CrearDocumentos_SyncRequest();
        inValue.DocumentosRequest = DocumentosRequest;
        return ((SI_Documento_Out)(this)).CrearDocumentos_SyncAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task SI_Documento_Out.CrearDocumentos_AsyncAsync(CrearDocumentos_Async request)
    {
        return base.Channel.CrearDocumentos_AsyncAsync(request);
    }
    
    public System.Threading.Tasks.Task CrearDocumentos_AsyncAsync(DocumentosDocumentos[] Documentos)
    {
        CrearDocumentos_Async inValue = new CrearDocumentos_Async();
        inValue.Documentos = Documentos;
        return ((SI_Documento_Out)(this)).CrearDocumentos_AsyncAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
        {
            return new System.ServiceModel.EndpointAddress("http://brasipind.expresobrasilia.com:50000/XISOAPAdapter/MessageServlet?senderPar" +
                    "ty=&senderService=Modelo&receiverParty=&receiverService=&interface=SI_Documento_" +
                    "Out&interfaceNamespace=urn%3ACreaDoc%3Amodelo%3Asap");
        }
        if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
        {
            return new System.ServiceModel.EndpointAddress("https://brasipind.expresobrasilia.com:50001/XISOAPAdapter/MessageServlet?senderPa" +
                    "rty=&senderService=Modelo&receiverParty=&receiverService=&interface=SI_Documento" +
                    "_Out&interfaceNamespace=urn%3ACreaDoc%3Amodelo%3Asap");
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        HTTP_Port,
        
        HTTPS_Port,
    }
}
