//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSServicioAdministracionVentasyTurnos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/", ConfigurationName="WSServicioAdministracionVentasyTurnos.ServicioAdministracionVentasyTurnos")]
    public interface ServicioAdministracionVentasyTurnos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/RegistroInformac" +
            "ionTurno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoResponse1> RegistroInformacionTurnoAsync(WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/RegistroInformac" +
            "ionVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaResponse1> RegistroInformacionVentaAsync(WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/")]
    public partial class RegistroInformacionTurnoRequest
    {
        
        private Turno turnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Turno Turno
        {
            get
            {
                return this.turnoField;
            }
            set
            {
                this.turnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/")]
    public partial class Turno
    {
        
        private int codigoEDSField;
        
        private System.DateTime fechaAperturaField;
        
        private int numeroTurnoField;
        
        private int numeroSurtidorField;
        
        private int numeroMangueraField;
        
        private double lecturaInicialField;
        
        private double lecturaFinalField;
        
        private double consumoField;
        
        private double ventaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoEDS
        {
            get
            {
                return this.codigoEDSField;
            }
            set
            {
                this.codigoEDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaApertura
        {
            get
            {
                return this.fechaAperturaField;
            }
            set
            {
                this.fechaAperturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroTurno
        {
            get
            {
                return this.numeroTurnoField;
            }
            set
            {
                this.numeroTurnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numeroSurtidor
        {
            get
            {
                return this.numeroSurtidorField;
            }
            set
            {
                this.numeroSurtidorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroManguera
        {
            get
            {
                return this.numeroMangueraField;
            }
            set
            {
                this.numeroMangueraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double lecturaInicial
        {
            get
            {
                return this.lecturaInicialField;
            }
            set
            {
                this.lecturaInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double lecturaFinal
        {
            get
            {
                return this.lecturaFinalField;
            }
            set
            {
                this.lecturaFinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double consumo
        {
            get
            {
                return this.consumoField;
            }
            set
            {
                this.consumoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double venta
        {
            get
            {
                return this.ventaField;
            }
            set
            {
                this.ventaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/")]
    public partial class Venta
    {
        
        private long consecutivoField;
        
        private System.DateTime fechaEmisionField;
        
        private System.DateTime fechaRealField;
        
        private int numeroTurnoField;
        
        private int numeroSurtidorField;
        
        private int numeroMangueraField;
        
        private string placaField;
        
        private string horaInicioField;
        
        private string horaFinField;
        
        private double lecturaInicioField;
        
        private double lecturaFinField;
        
        private double totalConsumoField;
        
        private double totalCuotaField;
        
        private double granTotalField;
        
        private double valorCombustibleField;
        
        private double galConsField;
        
        private int codigoEDSField;
        
        private string idRomSuicField;
        
        private int formaPagoField;
        
        private System.Nullable<int> kilometrajeField;
        
        private bool kilometrajeFieldSpecified;
        
        private System.Nullable<double> descuentoField;
        
        private bool descuentoFieldSpecified;
        
        private System.Nullable<double> numTarField;
        
        private bool numTarFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long consecutivo
        {
            get
            {
                return this.consecutivoField;
            }
            set
            {
                this.consecutivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime fechaEmision
        {
            get
            {
                return this.fechaEmisionField;
            }
            set
            {
                this.fechaEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime fechaReal
        {
            get
            {
                return this.fechaRealField;
            }
            set
            {
                this.fechaRealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numeroTurno
        {
            get
            {
                return this.numeroTurnoField;
            }
            set
            {
                this.numeroTurnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroSurtidor
        {
            get
            {
                return this.numeroSurtidorField;
            }
            set
            {
                this.numeroSurtidorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int numeroManguera
        {
            get
            {
                return this.numeroMangueraField;
            }
            set
            {
                this.numeroMangueraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string horaInicio
        {
            get
            {
                return this.horaInicioField;
            }
            set
            {
                this.horaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string horaFin
        {
            get
            {
                return this.horaFinField;
            }
            set
            {
                this.horaFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double lecturaInicio
        {
            get
            {
                return this.lecturaInicioField;
            }
            set
            {
                this.lecturaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double lecturaFin
        {
            get
            {
                return this.lecturaFinField;
            }
            set
            {
                this.lecturaFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double totalConsumo
        {
            get
            {
                return this.totalConsumoField;
            }
            set
            {
                this.totalConsumoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double totalCuota
        {
            get
            {
                return this.totalCuotaField;
            }
            set
            {
                this.totalCuotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public double granTotal
        {
            get
            {
                return this.granTotalField;
            }
            set
            {
                this.granTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public double valorCombustible
        {
            get
            {
                return this.valorCombustibleField;
            }
            set
            {
                this.valorCombustibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public double galCons
        {
            get
            {
                return this.galConsField;
            }
            set
            {
                this.galConsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int codigoEDS
        {
            get
            {
                return this.codigoEDSField;
            }
            set
            {
                this.codigoEDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string idRomSuic
        {
            get
            {
                return this.idRomSuicField;
            }
            set
            {
                this.idRomSuicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int formaPago
        {
            get
            {
                return this.formaPagoField;
            }
            set
            {
                this.formaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public System.Nullable<int> kilometraje
        {
            get
            {
                return this.kilometrajeField;
            }
            set
            {
                this.kilometrajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kilometrajeSpecified
        {
            get
            {
                return this.kilometrajeFieldSpecified;
            }
            set
            {
                this.kilometrajeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public System.Nullable<double> descuento
        {
            get
            {
                return this.descuentoField;
            }
            set
            {
                this.descuentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descuentoSpecified
        {
            get
            {
                return this.descuentoFieldSpecified;
            }
            set
            {
                this.descuentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public System.Nullable<double> numTar
        {
            get
            {
                return this.numTarField;
            }
            set
            {
                this.numTarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numTarSpecified
        {
            get
            {
                return this.numTarFieldSpecified;
            }
            set
            {
                this.numTarFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/")]
    public partial class Error
    {
        
        private System.Nullable<int> codigoErrorField;
        
        private bool codigoErrorFieldSpecified;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> codigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoErrorSpecified
        {
            get
            {
                return this.codigoErrorFieldSpecified;
            }
            set
            {
                this.codigoErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string mensajeError
        {
            get
            {
                return this.mensajeErrorField;
            }
            set
            {
                this.mensajeErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/")]
    public partial class Respuesta
    {
        
        private int codigoRespuestaField;
        
        private Error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/")]
    public partial class RegistroInformacionTurnoResponse
    {
        
        private Respuesta respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Respuesta Respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroInformacionTurnoRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/", Order=0)]
        public WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoRequest RegistroInformacionTurnoRequest;
        
        public RegistroInformacionTurnoRequest1()
        {
        }
        
        public RegistroInformacionTurnoRequest1(WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoRequest RegistroInformacionTurnoRequest)
        {
            this.RegistroInformacionTurnoRequest = RegistroInformacionTurnoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroInformacionTurnoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/", Order=0)]
        public WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoResponse RegistroInformacionTurnoResponse;
        
        public RegistroInformacionTurnoResponse1()
        {
        }
        
        public RegistroInformacionTurnoResponse1(WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoResponse RegistroInformacionTurnoResponse)
        {
            this.RegistroInformacionTurnoResponse = RegistroInformacionTurnoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/")]
    public partial class RegistroInformacionVentaRequest
    {
        
        private Venta ventaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Venta venta
        {
            get
            {
                return this.ventaField;
            }
            set
            {
                this.ventaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/")]
    public partial class RegistroInformacionVentaResponse
    {
        
        private Respuesta respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Respuesta respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroInformacionVentaRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/", Order=0)]
        public WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaRequest RegistroInformacionVentaRequest;
        
        public RegistroInformacionVentaRequest1()
        {
        }
        
        public RegistroInformacionVentaRequest1(WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaRequest RegistroInformacionVentaRequest)
        {
            this.RegistroInformacionVentaRequest = RegistroInformacionVentaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroInformacionVentaResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gasnatural.com.co/ServicioAdministracionVentasyTurnos/", Order=0)]
        public WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaResponse RegistroInformacionVentaResponse;
        
        public RegistroInformacionVentaResponse1()
        {
        }
        
        public RegistroInformacionVentaResponse1(WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaResponse RegistroInformacionVentaResponse)
        {
            this.RegistroInformacionVentaResponse = RegistroInformacionVentaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ServicioAdministracionVentasyTurnosChannel : WSServicioAdministracionVentasyTurnos.ServicioAdministracionVentasyTurnos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioAdministracionVentasyTurnosClient : System.ServiceModel.ClientBase<WSServicioAdministracionVentasyTurnos.ServicioAdministracionVentasyTurnos>, WSServicioAdministracionVentasyTurnos.ServicioAdministracionVentasyTurnos
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioAdministracionVentasyTurnosClient() : 
                base(ServicioAdministracionVentasyTurnosClient.GetDefaultBinding(), ServicioAdministracionVentasyTurnosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioAdministracionVentasyTurnosSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAdministracionVentasyTurnosClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioAdministracionVentasyTurnosClient.GetBindingForEndpoint(endpointConfiguration), ServicioAdministracionVentasyTurnosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAdministracionVentasyTurnosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioAdministracionVentasyTurnosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAdministracionVentasyTurnosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioAdministracionVentasyTurnosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAdministracionVentasyTurnosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoResponse1> WSServicioAdministracionVentasyTurnos.ServicioAdministracionVentasyTurnos.RegistroInformacionTurnoAsync(WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoRequest1 request)
        {
            return base.Channel.RegistroInformacionTurnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoResponse1> RegistroInformacionTurnoAsync(WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoRequest RegistroInformacionTurnoRequest)
        {
            WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoRequest1 inValue = new WSServicioAdministracionVentasyTurnos.RegistroInformacionTurnoRequest1();
            inValue.RegistroInformacionTurnoRequest = RegistroInformacionTurnoRequest;
            return ((WSServicioAdministracionVentasyTurnos.ServicioAdministracionVentasyTurnos)(this)).RegistroInformacionTurnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaResponse1> WSServicioAdministracionVentasyTurnos.ServicioAdministracionVentasyTurnos.RegistroInformacionVentaAsync(WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaRequest1 request)
        {
            return base.Channel.RegistroInformacionVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaResponse1> RegistroInformacionVentaAsync(WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaRequest RegistroInformacionVentaRequest)
        {
            WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaRequest1 inValue = new WSServicioAdministracionVentasyTurnos.RegistroInformacionVentaRequest1();
            inValue.RegistroInformacionVentaRequest = RegistroInformacionVentaRequest;
            return ((WSServicioAdministracionVentasyTurnos.ServicioAdministracionVentasyTurnos)(this)).RegistroInformacionVentaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioAdministracionVentasyTurnosSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioAdministracionVentasyTurnosSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://10.211.1.149:7006/GNVWebServices/services/ServicioAdministracionVentasyTur" +
                        "nosSOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioAdministracionVentasyTurnosClient.GetBindingForEndpoint(EndpointConfiguration.ServicioAdministracionVentasyTurnosSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioAdministracionVentasyTurnosClient.GetEndpointAddress(EndpointConfiguration.ServicioAdministracionVentasyTurnosSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioAdministracionVentasyTurnosSOAP,
        }
    }
}
